### ISSUE TITLE
Show Version on Server

### ISSUE THREAD

**Issue by Raeitus** [kd2org/opodsync#37]
Currently, when you log into the server, it does not show what version you are currently running.

It should display the current version from the [tag](https://github.com/bohwaz/micro-gpodder-server/tags) after you log into the server.

Do not display this before logging in, so that you don't announce to everyone the version and possible vulnerability for those who make their server public.

**Comment by bohwaz** [comment]
You can know this by using "git describe --tags", but I'm not deploying using git.
