### ISSUE TITLE
Stops working after a period of time

### ISSUE THREAD

**Issue by tuxcomputers** [kd2org/opodsync#38]
I have connected AntennaPod to the server, it will work for a period of time and then start failing.

To get it working again I have to logout of AntennaPod and then connect it again.

I turned on the debug and saw this
![image](https://github.com/bohwaz/micro-gpodder-server/assets/26516524/daa3e070-18a5-44e8-ba14-c37476b93d81)

I then looked at your code and saw this
![image](https://github.com/bohwaz/micro-gpodder-server/assets/26516524/f4f3afd2-6a0d-4ae7-8767-faf36981d85f)

I am not familiar with PHP enough but I think this means AntennaPod is broken and not sending the user name across, right?

**Comment by tuxcomputers** [comment]
After logging out and reconnecting I synced AntennaPod and once finished all the initial stuff I hit Synchronise now, the debug looks like this
![image](https://github.com/bohwaz/micro-gpodder-server/assets/26516524/96196cf1-f9ca-41b5-985e-c52e126696c0)

**Comment by tuxcomputers** [comment]
So my thinking was that because Antennapod doe snot have access to my server at home while I am out and about something something then it starts failing.

To check that I made a server that is publicly available at all times:
https://gpodder.tux.com.au

Nope it still ends up timing out, I have enabled the debug on the new server. The plan is to reconnect the phone to server then parse the logs to find out the time period it takes to start failing

**Comment by tuxcomputers** [comment]
I just updated to the latest code and will continue to monitor.

**Comment by tuxcomputers** [comment]
Ahhh what is this?
![image](https://github.com/kd2org/opodsync/assets/26516524/926a2d70-3270-4b34-b94d-209320a87d6c)
Notice the failure starts right after it

**Comment by tuxcomputers** [comment]
Oh right that is not AntennaPod, that is just some random trying shit.

**Comment by tuxcomputers** [comment]
It seems like the time is about 1/2 hour
![image](https://github.com/kd2org/opodsync/assets/26516524/28d0a811-e0f9-456a-af01-5e1b80f5dff9)

**Comment by bohwaz** [comment]
I have the same issue, not sure what is causing this currently.

**Comment by tuxcomputers** [comment]
Here is what I did as a hacky awful workaround.
1. AntennaPod fails
2. Kill the app
3. Open the app
4. Sync

I got the PHP to show me the cookie value, here it is before and after I killed the app
![image](https://github.com/kd2org/opodsync/assets/26516524/f99f5173-afb3-42a2-9dfb-40eaaaf7c27e)

So AntennaPod does not even try to use the sessionid cookie when it has been killed. I wonder what the expiry of the cookie is and if AntennaPod cares.

**Comment by tuxcomputers** [comment]
@bohwaz are you using Antenna Pod as well? It could be a change in that not your server.

**Comment by bohwaz** [comment]
Yes AntennaPod as well.

I just changed the HTTP status code in this case to 401, maybe that will trigger AntennaPod to restart the authentication dance if the cookie has expired.

Tell me if the error comes back after upgrading to the latest version.

**Comment by sezuan** [comment]
Hi!

I observer the same problem, but it doesn't help. Seems that Antennapod is not reauthenticating:

```
127.0.0.1 - matthias [06/Jun/2024:09:54:30 +0200] "POST /api/2/auth/matthias/login.json HTTP/1.1" 400 73 "-" "AntennaPod/3.4.0"
127.0.0.1 - matthias [06/Jun/2024:09:54:32 +0200] "POST /api/2/auth/matthias/login.json HTTP/1.1" 400 73 "-" "AntennaPod/3.4.0"
<updated API.php>
127.0.0.1 - matthias [06/Jun/2024:09:55:08 +0200] "POST /api/2/auth/matthias/login.json HTTP/1.1" 401 73 "-" "AntennaPod/3.4.0"
127.0.0.1 - matthias [06/Jun/2024:09:55:11 +0200] "POST /api/2/auth/matthias/login.json HTTP/1.1" 401 73 "-" "AntennaPod/3.4.0"
127.0.0.1 - matthias [06/Jun/2024:09:55:12 +0200] "POST /api/2/auth/matthias/login.json HTTP/1.1" 401 73 "-" "AntennaPod/3.4.0"

```

**Comment by bohwaz** [comment]
This happens when the client is sending a cookie linked to an expired session (PHP sessions expire after 30 minutes by default, if I remember correctly).

**Comment by bohwaz** [comment]
It might be that AntennaPod is providing the Authorization AND the expired session cookie. oPodSync is using the cookie first. I changed so that if Authorization is provided, cookie is ignored and replaced.

Let me know if that changes things. I also changed the error message to make it clearer.

**Comment by sezuan** [comment]
It works now. I couldn't duplicated it anymore. Thank you!

**Comment by jesusmgg** [comment]
I was also experiencing the issue and an update to the latest code seems to have fixed it.
