### ISSUE TITLE
A init problem

### ISSUE THREAD

**Issue by Pr0pHesyer** [kd2org/opodsync#40]
Debian12
I installed without php-sqlite3,then nothing works.
I can enter main page after installing php-sqlite3 but the register&login bottons are still unavailable.
I rm -rf * then reinstall,everything works finally.

Init failed then later failed,only reinstalling is usefull.

**Comment by bohwaz** [comment]
You installed without the required dependencies, and it didn't work. I don't see what the issue is here.
