### ISSUE TITLE
Wrong username or password

### ISSUE THREAD

**Issue by gokekun** [kd2org/opodsync#41]
I'm having issues trying to login with AntennaPod.

1) I installed micro-gpodder-server at https://gpodder.sugimoto.com.br .
2) I created a username and a password and logged in.
3) I installed gPodder desktop app for Mac. After installing, I logged in using "GPodder secret username" AND my password. I worked correctly and uploaded all my subscription to the server
4) I installed AntennaPod for Android (03/24/2024 version). When I try to login to a Gpodder.net server, it shows me a message of "Wrong username or password". I tried using my username or my secret username WITH or without my password. Any of them worked.

ps.: when I tried login with Gpoddersync, it worked well, but I couldn't sync ("Failed).

**Comment by gokekun** [comment]
from debug.log when I try to login (gpodder.net server):
`2024-05-12 18:34:57 Got a POST request on api/2/auth/gokekun29031986/login.json
2024-05-12 18:34:57 RETURN: 401 - No username or password provided`

from debug.log when I try to sync (after successfully login gpoddersync):
`2024-05-12 18:31:46 Got a GET request on index.php/apps/gpoddersync/subscriptions
2024-05-12 18:31:46 RETURN: 401 - No username or password provided`

**Comment by gokekun** [comment]
For those having similar problem as mine.

I use a sharedhost at Dreamhost. I remembered later that Dreamhost uses PHP-CGI and have trouble with authentication outside it's own domain.

Searching for a sollution, I found this post at stackoverflow:
https://stackoverflow.com/questions/14724127/why-are-serverphp-auth-user-and-serverphp-auth-pw-not-set

And this tutorial.
https://orangejuiceliberationfront.com/http-auth-with-php-in-cgi-mode-e-g-on-dreamhost/

I finally could login using AntennaPod:
`2024-05-13 14:30:31 RETURN: 200 - Logged in!`
But it still required a session cookie:
`2024-05-13 14:30:31 RETURN: 401 - session cookie is requiredArray`

Nevertheless I could login using  Gpoddersync and successfully sync my podcasts.

Ps: I'm aware that I'm a complete newbie. Sorry for the "Issue" and the lack of technical skills.

**Comment by bohwaz** [comment]
Did you try this: https://stackoverflow.com/questions/51806446/serverhttp-authorization-is-missing
?

**Comment by gokekun** [comment]
No, I didn't. I'll try it, thanks.


What I did so far to solve my authentication issue was:

Updated .htaccess with:
`RewriteEngine on`
`RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]`

Added these lines to API.php right before "if (empty($_SERVER['PHP_AUTH_USER']) || empty($_SERVER['PHP_AUTH_PW']))"

`list($_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW']) = explode(':', base64_decode(substr($_SERVER['HTTP_AUTHORIZATION'], 6)));`
`		if( strlen($_SERVER['PHP_AUTH_USER']) == 0 || strlen($_SERVER['PHP_AUTH_PW']) == 0 ) {`
`        unset($_SERVER['PHP_AUTH_USER']);`
`        unset($_SERVER['PHP_AUTH_PW']);`
`    }`
