### ISSUE TITLE
Device column not populated in episodes_actions table

### ISSUE THREAD

**Issue by tuxcomputers** [kd2org/opodsync#45]
There are 9,300 entries in the table, not a single record has the device
![2024-05-15 13 38 26](https://github.com/kd2org/opodsync/assets/26516524/05691ab8-bbd1-4c4a-bc0c-96ac77e6fcd8)

**Comment by bohwaz** [comment]
This is the case if you are using the NextCloud sync.

**Comment by tuxcomputers** [comment]
I am connecting AntennaPod using GPodder.
