### ISSUE TITLE
Possibility to delete a feed

### ISSUE THREAD

**Issue by zorglube** [kd2org/opodsync#46]
Since I declared you this "false bug" https://github.com/kd2org/opodsync/issues/43, I deleted the feed from my AtennaPod app, but after synchromization the feed is still present into my oPodSync instance.

I wonder, would it be possible to offer a `delete` capability into the oPodSync GUI ?

**Comment by bohwaz** [comment]
Feel free to make a PR :)

**Comment by zorglube** [comment]
https://github.com/kd2org/opodsync/pull/48
