### ISSUE TITLE
Installation: a few more details would be nice

### ISSUE THREAD

**Issue by wehkah** [kd2org/opodsync#54]
Hello!

The instructions how to install tell us: "Just copy the files from the server directory into a new directory of your webserver."

Well, that alone will not get the server running. What do I need to do after copying those files? Thanks in advance for any help!

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by bohwaz** [comment]
Beware this is probably a virus or scam! Don't download the above link. I'll delete the comment when I'm on my computer.

**Comment by bohwaz** [comment]
Hum it seems the link has already been deleted by GitHub.

**Comment by bohwaz** [comment]
Just tested and yes just copying files is enough. Just visit the web page where you set up the app, and create your user.

**Comment by wehkah** [comment]
> Just visit the web page where you set up the app, and create your user.

I'm sorry, but that is exactly the kind of additional information I was referring to. What app are you talking about? A web server like Nginx? If so: how do I tell the server to load the synching code and execute it? How do I connect to the server?

You see: there are a lot of questions about how to make this software working.

**Comment by bohwaz** [comment]
The readme is pretty clear I think:

>When installed, the server will allow to create a first account. Just go to the server URL and you will be able to create an account and login.

**Comment by bohwaz** [comment]
If not, feel free to make a PR :)

**Comment by wehkah** [comment]
Oh dear... there seems to be some great misunderstanding here. So, please let's start from the beginning:

In my life I've set up a few web servers, and as far as I know, no web server that has been set up properly, will run a script or an app that is just being copied into a directory within its domain. If that was working that easily, hacking a web server could be done by 3 year old kids. Every web server I know needs to be told which alias and / or which port is supposed to run which CGI, so it can differ between a call like this

"http(s)://my.pretty.server/function1" or "http(s)://my.pretty.server:8088"

and a call like this:

"http(s)://my.pretty.server/function2" or "http(s)://my.pretty.server:8099"

It needs to know where the right CGI for function1 is to be found and where the CGI for function2 can be found.

Let's say I wanted to use lighttpd, then I would have to make appropriate entries in lighttpd.conf.

Do you understand my lack of understanding the "just-copy-files" part now?

**Comment by bohwaz** [comment]
These instructions are meant for non-technical people, using shared hosting, where you just upload the files through FTP, that's what is meant by "just copy files and go to the URL".

If you know how to install a web server, you probably can figure out how to set up a virtual host with document root :)

If not feel free to make a PR with missing instructions.

**Comment by wehkah** [comment]
> These instructions are meant for non-technical people, using shared hosting, where you just upload the files through FTP, that's what is meant by "just copy files and go to the URL".

Aha! This is exactly the information that should be included in the "installation instructions", because it is the mere source of this misunderstanding we are facing here!
